name: pyatsa
channels:
  - conda-forge
dependencies:
  # pyatsa requirements
  - numpy>=1.8
  - scipy>=1.3.0
  - scikit-image>=0.15
  - statsmodels=0.10.0
  - scikit-learn>=0.21.2
  - xarray>=0.12.3
  - dask>=2.1.0
  - ipykernel
  - pip:
    - flit #used to publish to pypi and install locally for development
    - rasterio>=1.0.7
    # porder requirements
    - Shapely>=1.6.4
    - requests>=2.19.1
    - planet>=1.2.3
    - progressbar2>=3.38.0
    - pySmartDL>=1.2.5
    - clipboard>=0.0.4
    - retrying>=1.3.3
    - pyyaml>=3.12
    - prettytable>=0.7.2
    - pyproj>=1.9.5.1
    - geopandas>=0.5.0
    - pendulum>=2.0.4
    - visvalingamwyatt>=0.1.2


